### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by travjenkins** [estuary/ui#1312]
![image](https://github.com/user-attachments/assets/1ae586f0-d059-4772-bbfb-4b57649e9dc5)

**Comment by travjenkins** [comment]
We will no longer directly run:

```
gcloud run deploy dashboard \
  --project estuary-control \
  --region us-central1 \
  --source ./build/
```

We will use a new action

```
uses: 'google-github-actions/deploy-cloudrun@v2'
with:
    service: 'dashboard'
    project_id: 'estuary-control'
    region: 'us-central1'
    source: './build/'
```
