### ISSUE TITLE
Materialization edit: bindings selector breaks when using partition selectors

### ISSUE THREAD

**Issue by psFried** [estuary/ui#935]
**Bug**

This was observed when editing an existing materialization in the UI that has multiple bindings for the same collection, just with different partition selectors. For example:

```
bindings:
  - source:
      name: acmeCo/foo
      partitions: { include: { part: [ 'A' ] } }
    resource: { table: foo_a }
  - source:
      name: acmeCo/foo
      partitions: { include: { part: [ 'B' ] } }
    resource: { table: foo_b }
```

**Expected**

Expected to be able to edit the resource config for each binding, and for the spec to not get mutated without me making any changes.

What actually happens is that the resource config editor does not change when clicking between the bindings. It always shows the same one. Also, the draft spec seems have been changed such that the same resource config is duplicated on both bindings.

**Screenshots**

Sorry, but the only example I have is on a production materialization, and I don't want to post an image of their materialization publicly.

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: firefox
